### ISSUE TITLE
`load_file()` returns an `[Errno 22] Invalid argument` error

### ISSUE THREAD

**Issue by lymereJ** [BrickSchema/py-brickschema#114]
Hi - 

When I run the following code I get an `[Errno 22] Invalid argument` error. The turtle file used is this [one](https://github.com/pnnl/ConStrain/blob/reorg_examples_clean/resources/brick/Brick.ttl).

```python
import brickschema
g = brickschema.Graph(load_brick=False)
g.load_file("./constrain/resources/brick/Brick.ttl")
```

Here's the full traceback:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\brickschema\graph.py", line 572, in load_file
    self.parse(filename, format=fmt)
  File "C:\Python310\lib\site-packages\rdflib\graph.py", line 1492, in parse
    parser.parse(source, self, **args)
  File "C:\Python310\lib\site-packages\rdflib\plugins\parsers\notation3.py", line 2021, in parse
    p.loadStream(stream)
  File "C:\Python310\lib\site-packages\rdflib\plugins\parsers\notation3.py", line 479, in loadStream
    return self.loadBuf(stream.read())  # Not ideal
OSError: [Errno 22] Invalid argument
```
I'm using `brickschema` 0.7.5 and `rdflib` 7.0.0 with Python 3.10.8. Any idea as to why this is happening?

**Comment by lymereJ** [comment]
I tried different versions of Python and I'm still getting the same error.

**Comment by lymereJ** [comment]
Issue with Microsoft's OneDrive software. See https://github.com/RDFLib/rdflib/issues/2790.
