### ISSUE TITLE
brick_validate crashes when validating the GHC building

### ISSUE THREAD

**Issue by xyzisinus** [BrickSchema/py-brickschema#17]

**Comment by xyzisinus** [comment]
```
brick_validate ~/Brick/examples/ghc_brick.ttl 
Traceback (most recent call last):
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/bin/brick_validate", line 11, in <module>
    load_entry_point('brickschema', 'console_scripts', 'brick_validate')()
  File "/Users/czang/py-brickschema/bin/brick_validate.py", line 60, in main
    result = v.validate(dataG, ont_graphs=ontGraphs, shacl_graphs=shaclGraphs,
  File "/Users/czang/py-brickschema/brickschema/validate.py", line 111, in validate
    self.violationList = self.__attachOffendingTriples()
  File "/Users/czang/py-brickschema/brickschema/validate.py", line 153, in __attachOffendingTriples
    self.__triplesForOneViolation(violation)
  File "/Users/czang/py-brickschema/brickschema/validate.py", line 263, in __triplesForOneViolation
    res = self.__queryDataGraph(self.__prefix(focusNode), path, None)
  File "/Users/czang/py-brickschema/brickschema/validate.py", line 173, in __queryDataGraph
    q = prepareQuery('SELECT ?s ?p ?o WHERE {%s %s %s .}' %
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/rdflib/plugins/sparql/processor.py", line 25, in prepareQuery
    ret = translateQuery(parseQuery(queryString), base, initNs)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/rdflib/plugins/sparql/parser.py", line 1058, in parseQuery
    return Query.parseString(q, parseAll=True)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1947, in parseString
    raise exc
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1937, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4052, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4252, in parseImpl
    raise maxException
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4237, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4052, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4052, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1681, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 1681, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/czang/Library/Caches/pypoetry/virtualenvs/brickschema-NIyk7U8S-py3.8/lib/python3.8/site-packages/pyparsing.py", line 2883, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery}, found 'G'  (at char 23), (line:1, col:24)
```

**Comment by xyzisinus** [comment]
Not a bug in brick_validate.  sparql.prepareQuery doesn't like "/".  After using my make_prefixable tool to remove special characters, the ghc build is validated.

**Comment by gtfierro** [comment]
I don't think the `make_prefixable` tool is appropriate here. The correct solution is to (a) make sure all URIs contain only valid characters, and (b) to escape them when they are included.

In this case, you should rewrite the query as:

(assumes the URI for `GHC` is `http://example.org/GHC#`)

```sparql
SELECT ?s ?p ?o 
WHERE {
    <http://example.org/GHC#SCSC_Hillman/VAV_Room_5412/Schedule> brick:isPointOf ?o 
}
````

**Comment by xyzisinus** [comment]
Fixed with [pr 19](https://github.com/BrickSchema/py-brickschema/pull/19)
