### ISSUE TITLE
requests not installed with brickschema

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/py-brickschema#23]
Hey Gabe,

python: 3.6.5
brickschema: 0.1.5

`pip install brickschema`

```
Collecting brickschema
  Downloading brickschema-0.1.5-py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 653 kB/s
Collecting rdflib<6.0,>=5.0
  Downloading rdflib-5.0.0-py3-none-any.whl (231 kB)
     |████████████████████████████████| 231 kB 1.2 MB/s
Collecting pytest<6.0,>=5.3
  Downloading pytest-5.4.3-py3-none-any.whl (248 kB)
     |████████████████████████████████| 248 kB 768 kB/s
Collecting owlrl<6.0,>=5.2
  Downloading owlrl-5.2.1-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 1.3 MB/s
Collecting sqlalchemy<2.0,>=1.3
  Downloading SQLAlchemy-1.3.17-cp36-cp36m-macosx_10_14_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 872 kB/s
Collecting pyshacl<0.12.0,>=0.11.4
  Downloading pyshacl-0.11.5-py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 1.3 MB/s
Requirement already satisfied: six in /Users/cmosiman/.pyenv/versions/3.6.5/envs/haste/lib/python3.6/site-packages (from rdflib<6.0,>=5.0->brickschema) (1.14.0)
Collecting isodate
  Using cached isodate-0.6.0-py2.py3-none-any.whl (45 kB)
Collecting pyparsing
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 773 kB/s
Collecting more-itertools>=4.0.0
  Downloading more_itertools-8.4.0-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 1.0 MB/s
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /Users/cmosiman/.pyenv/versions/3.6.5/envs/haste/lib/python3.6/site-packages (from pytest<6.0,>=5.3->brickschema) (1.6.0)
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.5.0
  Downloading py-1.8.2-py2.py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 694 kB/s
Collecting wcwidth
  Downloading wcwidth-0.2.4-py2.py3-none-any.whl (30 kB)
Collecting rdflib-jsonld>=0.4.0
  Downloading rdflib-jsonld-0.5.0.tar.gz (55 kB)
     |████████████████████████████████| 55 kB 1.0 MB/s
Requirement already satisfied: zipp>=0.5 in /Users/cmosiman/.pyenv/versions/3.6.5/envs/haste/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest<6.0,>=5.3->brickschema) (3.1.0)
Building wheels for collected packages: rdflib-jsonld
  Building wheel for rdflib-jsonld (setup.py) ... done
  Created wheel for rdflib-jsonld: filename=rdflib_jsonld-0.5.0-py2.py3-none-any.whl size=15348 sha256=f8c49154dd8e911420faae581b9b8cc2417b4768b1d381fbf2bfb9ff4157ce63
  Stored in directory: /Users/cmosiman/Library/Caches/pip/wheels/e4/72/6e/144dce8b21558be176168b23bd8d7062c21cbbe9596c3926ec
Successfully built rdflib-jsonld
Installing collected packages: isodate, pyparsing, rdflib, more-itertools, attrs, packaging, pluggy, py, wcwidth, pytest, rdflib-jsonld, owlrl, sqlalchemy, pyshacl, brickschema
Successfully installed attrs-19.3.0 brickschema-0.1.5 isodate-0.6.0 more-itertools-8.4.0 owlrl-5.2.1 packaging-20.4 pluggy-0.13.1 py-1.8.2 pyparsing-2.4.7 pyshacl-0.11.5 pytest-5.4.3 rdflib-5.0.0 rdflib-jsonld-0.5.0 sqlalchemy-1.3.17 wcwidth-0.2.4
```

However, I then go to run a server and get:

```
cmosiman-34078s:haste cmosiman$ python manage.py runserver
/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Watching for file changes with StatReloader
2020-06-20:00:09:26,310 INFO    [autoreload.py:598] Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/cmosiman/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/cmosiman/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cmosiman/Github/Haste/haste/generate/models.py", line 6, in <module>
    from lib.helpers import Shadowfax
  File "/Users/cmosiman/Github/Haste/haste/lib/helpers.py", line 8, in <module>
    from brickschema.inference import HaystackInferenceSession
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/brickschema/__init__.py", line 13, in <module>
    from . import graph, inference, namespaces, validate
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/brickschema/validate.py", line 10, in <module>
    from rdflib.plugins.sparql import prepareQuery
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/rdflib/plugins/sparql/__init__.py", line 37, in <module>
    from .processor import prepareQuery, processUpdate
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/rdflib/plugins/sparql/processor.py", line 18, in <module>
    from rdflib.plugins.sparql.evaluate import evalQuery
  File "/Users/cmosiman/.pyenv/versions/haste/lib/python3.6/site-packages/rdflib/plugins/sparql/evaluate.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

I then `pip install requests` and works as expected. Not sure why...but wanted to point out to you.

**Comment by gtfierro** [comment]
Thanks for the complete bug report! This was just an oversight on my end; should be fixed in brickschema v0.1.6
